title: Minimal theme
logo: <img src="/images/headshot.jpg" alt="Headshot" width="150" />
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
